### PR TITLE
fix: preserve configuration for custom instance

### LINKED ISSUE #68: I set retry 3 times，but only retry 1 times
```js
raxConfig: {
    retry: 3,
    noResponseRetries: 5,
    instance: http,
    retryDelay: 100,
    httpMethodsToRetry: ['GET', 'OPTIONS', 'POST'],
    shouldResetTimeout: false,
    onRetryAttempt: (err) => {
      const cfg = rax.getConfig(err);
      console.log(cfg.currentRetryAttempt);
    }
  }
```

### PR DESCRIPTION
**Pull request by orgads**
Fixes #68.

### CODE REVIEW

File: src/index.ts [hunk 1]
```diff
@@ -175,7 +175,7 @@ async function onError(error: AxiosError) {
 	config.retry = typeof config.retry === 'number' ? config.retry : 3;
 	config.retryDelay =
 		typeof config.retryDelay === 'number' ? config.retryDelay : 100;
-	config.instance = config.instance || axios;
+	config.instance = config.instance || instance;
```
Comment (orgads) [inline src/index.ts:178]: I think config.instance can be deprecated following this change.

**Comment by JustinBeckwith** [comment]
I haven't been paying a ton of attention to axios API changes, but this generally seems good if the tests pass 😆  Could I trouble you to run `npm run fix` and push the changes back up?

**Comment by orgads** [comment]
Done
